version: '3.7'
services:

  app_nginx:
    container_name: app_nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network
    depends_on:
      - app_nodejs

  app_nodejs:
    container_name: app_nodejs
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
        - "3000:3000"
    volumes:
      - app_storage_volume:/var/storage/app-nodejs/
    networks:
      - app_network

  app_mysql:
    container_name: app_mysql
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./docker/mysql/shared:/root/shared/
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_volume:
    driver: local
  app_storage_volume:
    driver: local
